name: bdl-rul-svgd
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.8.13
  - pytorch=1.12.1
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.3
    - aiohttp-cors==0.7.0
    - aiorwlock==1.3.0
    - aiosignal==1.2.0
    - anyio==3.6.2
    - asgiref==3.5.2
    - async-timeout==4.0.2
    - attrs==22.1.0
    - bayestorch==0.0.1
    - black==22.10.0
    - blessed==1.19.1
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.0.4
    - colorful==0.5.4
    - contourpy==1.0.6
    - cycler==0.11.0
    - distlib==0.3.6
    - fastapi==0.86.0
    - filelock==3.8.0
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - google-api-core==2.10.2
    - google-auth==2.14.0
    - googleapis-common-protos==1.56.4
    - gpustat==1.0.0
    - grpcio==1.43.0
    - h11==0.14.0
    - idna==3.4
    - importlib-resources==5.10.0
    - isort==5.10.1
    - jsonschema==4.17.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - msgpack==1.0.4
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - numpy==1.23.4
    - nvidia-ml-py==11.495.46
    - opencensus==0.11.0
    - opencensus-context==0.1.3
    - packaging==21.3
    - pandas==1.5.1
    - pathspec==0.10.1
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.3
    - prometheus-client==0.13.1
    - protobuf==3.19.6
    - psutil==5.9.3
    - py-spy==0.3.14
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - ray==2.0.1
    - requests==2.28.1
    - rsa==4.9
    - scipy==1.9.3
    - seaborn==0.12.1
    - six==1.16.0
    - smart-open==6.2.0
    - sniffio==1.3.0
    - starlette==0.20.4
    - tabulate==0.9.0
    - tensorboardx==2.5.1
    - tomli==2.0.1
    - urllib3==1.26.12
    - uvicorn==0.16.0
    - virtualenv==20.16.6
    - wcwidth==0.2.5
    - yarl==1.8.1
    - zipp==3.10.0
